### PR TITLE
User selected cluster type for Enable/Disable GitOps command

### LINKED ISSUE #218: Set AKS cluster as generic
When using AKS, setting the Cluster Provider to **generic** does not work. Flux is still installed as an extension and some users might not want to use that extra layer in between.

To be precise, I am referring to the installation of Flux itself. I have noticed that after installation via the extension, fluxconfigs are not used anymore (as expected).

### PR DESCRIPTION
**Pull request by juozasg**
enableDisableGitOps should use clusterProvider from globalState

Fixes #218

### CODE REVIEW

**Comment by usernamehw** [comment]
Maybe it can be moved to a new function since it's being used in multiple places, something like:

```ts
export async function detectClusterProvider(contextName: string, clusterName: string): Promise<ClusterProvider> {
	const clusterMetadata = globalState.getClusterMetadata(clusterName);
	return clusterMetadata?.clusterProvider || await kubernetesTools.detectClusterProvider(contextName);
}
```

**Review by usernamehw — APPROVED** [review]

**Comment by juozasg** [comment]
@usernamehw Would it make sense to modify `kubernetesTools.detectClusterProvider` to do this?

**Comment by usernamehw** [comment]
You can. I tried to keep that file only for running `kubectl` commands but it still got some code that prints commands into `Output`, code that changes VSCode context and telemetry. One global state call won't change much. Maybe it can be refactored later.

**Comment by kingdonb** [comment]
I have tested this out and I was able to use it to get Flux installed on AKS, avoiding the addons manager. 👍 

I'm gonna call this `0.19.2-pre1` and add it to the roadmap for the next release. Please merge when ready!

**Review by kingdonb — APPROVED** [review]
👍

**Comment by juozasg** [comment]
I added `globalState` logic to `kubernetesTools.detectClusterProvider`. However I found a `contextName` and `clusterName` are used interchangibly in some of the code. So I added some helpers to fix and factor it out.

**Pull request merged**
